.PHONEY: docker _pack clean

docker:
	docker run --rm \
	  -v $(CURDIR):/app \
	  knzm/lambda-packer:python-3.5 \
	  make _pack

_pack:
	pack -r requirements.txt
	zip lambda_function.zip lambda_function.py

clean:
	@rm -f lambda_function.zip
